cask_args appdir: '~/Applications'

tap 'homebrew/cask'
tap 'homebrew/bundle'
tap 'homebrew/cask-drivers'
tap 'github/gh'
tap 'lotyp/homebrew-formulae'

brew 'imagemagick'
brew 'gh'
brew 'gnupg'
brew 'jenv'
brew 'jq'
brew 'lotyp/formulae/dockutil'
brew 'mas'
brew 'mitmproxy'
brew 'nvm'
brew 'openssl'
brew 'pinentry-mac'
brew 'pyenv'
brew 'pyenv-virtualenv'
brew 'readline'
brew 'rbenv'
brew 'z'
brew 'zsh-syntax-highlighting'

cask 'alfred'
cask 'app-cleaner'
cask 'charles'
cask 'discord'
cask 'firefox'
cask 'google-chrome'
cask 'gpg-suite'
cask 'iterm2'
cask 'logseq'
cask 'opensim'
cask 'postman'
cask 'proxyman'
cask 'sf-symbols'
cask 'slack'
cask 'sourcetree'
cask 'stoplight-studio'
cask 'telegram'
cask 'temurin'
cask 'tunnelblick'
cask 'visual-studio-code'
cask 'whatsapp'
cask 'xcodes'
cask 'zoom'

